spring:
  application:
    name: AUTHORIZATION-SERVICE
---
spring:
  cloud:
    config:
      label: main
  config:
    activate:
      on-profile: default, identity-web
    import: configserver:http://${CONFIG_SERVER_USERNAME:user}:${CONFIG_SERVER_PASSWORD:sa}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8099}?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100

---
spring:
  cloud:
    config:
      enabled: false
  config:
    activate:
      on-profile: local, identity-logger
eureka:
  client:
    enabled: false