spring:
  application:
    name: AUTHORIZATION-SERVICE
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:identity-web}
  cloud:
    config:
      label: main
  config:
    import: optional:configserver:http://${CONFIG_SERVER_USERNAME:user}:${CONFIG_SERVER_PASSWORD:sa}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8099}?fail-fast=true&max-attempts=20&max-interval=15000&multiplier=1.8&initial-interval=11000